[package]
name = "apollo"
version = "0.0.1"
authors = ["Sean Gillespie <sean@swgillespie.me>"]

[dependencies]
apollo_engine = { path = "../apollo_engine", version = "0.0.1" }
apollo_uci = { path = "../apollo_uci", version = "0.0.1" }