[package]
name = "apollo_engine"
version = "0.0.1"
authors = ["Sean Gillespie <sean@swgillespie.me>"]
license = "MIT/Apache-2.0"
description = "Core of a chess engine."
repository = "https://github.com/swgillespie/apollo"
keywords = ["chess"]

[dependencies]
bitflags = "0.9.1"
num-traits = "0.1.39"