name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run unit tests
      run: cargo test --verbose
    - name: Build Release
      run: cargo build --release
    - name: Run perft tests
      run: python3 ./tests/run.py
